import mongoose from "mongoose"
import Listing from "../lib/models/Listing"
import { dbConnect } from "../lib/mongodb"

const listings = [
  {
    userId: "0xindianuser1",
    eventTitle: "Diwali Night Extravaganza",
    ticketType: "VIP",
    originalPrice: "₹2000",
    date: "2025-11-01",
    time: "19:00",
    location: "Mumbai, Maharashtra",
    image: "/placeholder.svg?height=200&width=300",
    listingTitle: "VIP Pass for Diwali Night",
    description: "Experience the grandest Diwali celebration with live music, food, and fireworks!",
    category: "Festival",
    condition: "excellent",
    transferMethod: "email",
    salePrice: "₹2500",
    minimumPrice: "₹2000",
    instantSale: true,
    auctionDuration: "",
    royaltyPercentage: "0",
    tags: ["diwali", "festival", "vip"],
  },
  {
    userId: "0xindianuser2",
    eventTitle: "Arijit Singh Live Concert",
    ticketType: "General",
    originalPrice: "₹1500",
    date: "2025-10-15",
    time: "18:00",
    location: "Delhi NCR",
    image: "/placeholder.svg?height=200&width=300",
    listingTitle: "Arijit Singh Concert Ticket",
    description: "Enjoy a soulful evening with Arijit Singh performing his greatest hits.",
    category: "Concert",
    condition: "excellent",
    transferMethod: "mobile",
    salePrice: "₹1800",
    minimumPrice: "₹1500",
    instantSale: true,
    auctionDuration: "",
    royaltyPercentage: "0",
    tags: ["arijit", "concert", "music"],
  },
  {
    userId: "0xindianuser3",
    eventTitle: "Bollywood Dandiya Night",
    ticketType: "General",
    originalPrice: "₹800",
    date: "2025-10-20",
    time: "20:00",
    location: "Ahmedabad, Gujarat",
    image: "/placeholder.svg?height=200&width=300",
    listingTitle: "Dandiya Night Pass",
    description: "Dance the night away with Bollywood beats and Dandiya sticks!",
    category: "Festival",
    condition: "excellent",
    transferMethod: "blockchain",
    salePrice: "₹1000",
    minimumPrice: "₹800",
    instantSale: true,
    auctionDuration: "",
    royaltyPercentage: "0",
    tags: ["dandiya", "navratri", "bollywood"],
  },
  {
    userId: "0xindianuser4",
    eventTitle: "Sunburn Goa 2025",
    ticketType: "VIP",
    originalPrice: "₹5000",
    date: "2025-12-27",
    time: "16:00",
    location: "Goa",
    image: "/placeholder.svg?height=200&width=300",
    listingTitle: "Sunburn VIP Pass",
    description: "Asia's biggest music festival with top DJs and artists.",
    category: "Festival",
    condition: "excellent",
    transferMethod: "email",
    salePrice: "₹6000",
    minimumPrice: "₹5000",
    instantSale: true,
    auctionDuration: "",
    royaltyPercentage: "0",
    tags: ["sunburn", "goa", "music"],
  },
  {
    userId: "0xindianuser5",
    eventTitle: "Comedy Night with Zakir Khan",
    ticketType: "General",
    originalPrice: "₹1200",
    date: "2025-09-30",
    time: "20:00",
    location: "Bangalore, Karnataka",
    image: "/placeholder.svg?height=200&width=300",
    listingTitle: "Zakir Khan Comedy Show",
    description: "Laugh out loud with Zakir Khan's latest stand-up act.",
    category: "Comedy",
    condition: "excellent",
    transferMethod: "mobile",
    salePrice: "₹1500",
    minimumPrice: "₹1200",
    instantSale: true,
    auctionDuration: "",
    royaltyPercentage: "0",
    tags: ["comedy", "zakirkhan", "standup"],
  },
]

async function seed() {
  await dbConnect()
  await Listing.deleteMany({})
  await Listing.insertMany(listings)
  console.log("Seeded demo Indian event listings in INR.")
  mongoose.connection.close()
}

seed()
